Support slash commands with enhanced-discord.py
eibex/reaction-light pull request #87
Opened 2021-11-16 16:26 UTC by eibex

Supports slash commands by replacing discord.py with [enhanced-discord.py](https://github.com/iDevision/enhanced-discord.py).
This PR is not final and I might still change library or language.

Breaking changes:
- New library
- Python 3.8+ only

Closes #83 

Mutually exclusive PRs:
- #86

2021-11-18 21:08 UTC, eibex commented
@Edwinexd whenever you have time 🙇

2021-11-19 14:25 UTC, Edwinexd requested changes

2021-11-19 14:25 UTC, Edwinexd commented on requirements.txt
> +disnake>=2.2.1
```suggestion
git+https://github.com/iDevision/enhanced-discord.py@7aafbc2dcf82ec4b8e42b529099c984ff55ffe29
```

2021-11-19 14:25 UTC, Edwinexd commented on README.md
> +python3 -m pip install -U git+https://github.com/iDevision/enhanced-discord.py
```suggestion
python3 -m pip install -r requirements.txt
```

2021-11-19 14:25 UTC, Edwinexd commented on README.md
> +You can get enhanced-discord.py via PyPI or GitHub:
```suggestion
You can get the required dependencies using PyPI:
```

2021-11-19 14:25 UTC, Edwinexd commented on README.md
> +[![enhanced-d.py 1.7.3+](https://img.shields.io/badge/enhanced--d.py-1.7.3+-blue.svg)](#)
```suggestion
[![enhanced-d.py 2.0.0a+](https://img.shields.io/badge/enhanced--d.py-2.0.0a+-blue.svg)](#)
```

2021-11-19 14:25 UTC, Edwinexd commented on CHANGELOG.md
> +    - Reinvite it with the following link: `https://discord.com/oauth2/authorize?&client_id=CLIENT_ID&scope=bot%20applications.commands&permissions=2415929408` (replace CLIENT_ID)
```suggestion
    - Reauthorize it with the following link: `https://discord.com/oauth2/authorize?&client_id=CLIENT_ID&scope=bot%20applications.commands&permissions=2415929408` (replace CLIENT_ID)
```

2021-11-19 14:25 UTC, Edwinexd commented on CHANGELOG.md
> +    - Kick the bot from your instance
```suggestion
```

2021-11-19 14:25 UTC, Edwinexd commented on CHANGELOG.md
> +    - `python3 -m pip install -U git+https://github.com/iDevision/enhanced-discord.py`
```suggestion
    - `python3 -m pip install -r requirements.txt`
```

2021-11-30 17:48 UTC, eibex commented
closing this for now, but not deleting the branch

2021-11-30 17:48 UTC, closed without merging